### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by hoshsadiq** [go-task/slim-sprig#14]
Installing slim-sprig causes the installation of the tagged version v2.20.0 which is quite old (2019!). Currently having to explicitly define the latest commit. It's not a huge issue, but it caused some confusion. Would be great to cut a new tag so go modules gets the correct version. Since the tags are already at v2.20.0, it might be worth to rename the package to `github.com/go-task/slim-sprig/v3` and cut a `v3.0.0` as go module cache will have already cached 2.20.0

**Comment by andreynering** [comment]
Hi @hoshsadiq,

I decided to follow your suggestion. v3.0.0 was tagged.
